name: Passo 0

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: write
  issues: write

env:
  STEP_1_FILE: ".github/steps/1-step.md"

jobs:
  start_exercise:
    if: |
      !github.event.repository.is_template
    name: Iniciar Exercício
    uses: dev-pods/exercise-toolkit/.github/workflows/start-exercise.yml@v0.1.1
    with:
      exercise-title: "Sua Primeira Extensão para o GitHub Copilot"
      intro-message: "Prepare-se! Vamos aprender como tornar seu programador parceiro de IA favorito ainda melhor, estendendo-o com algumas habilidades personalizadas!"

  post_next_step_content:
    name: Publicar conteúdo do próximo passo
    runs-on: ubuntu-latest
    needs: [start_exercise]
    env:
      ISSUE_REPOSITORY: ${{ github.repository }}
      ISSUE_NUMBER: ${{ needs.start_exercise.outputs.issue-number }}

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v4

      - name: Obter templates de resposta
        uses: actions/checkout@v4
        with:
          repository: dev-pods/exercise-toolkit
          path: exercise-toolkit
          ref: v0.1.1

      - name: Criar comentário - adicionar conteúdo do passo
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: ${{ env.STEP_1_FILE }}
          vars: |
            full_repo_name: ${{ github.repository }}

      - name: Criar comentário - aguardando progresso
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: exercise-toolkit/markdown-templates/step-feedback/watching-for-progress.md

      - name: Habilitar próximo workflow
        run: |
          gh workflow enable "Step 1"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
