name: Step 3

on:
  issue_comment:
    types: [created, edited]

permissions:
  contents: read
  actions: write
  issues: write

env:
  STEP_4_FILE: ".github/steps/4-step.md"

jobs:
  check_keywords:
    name: Verificar palavra-chave no comentário da issue
    runs-on: ubuntu-latest
    steps:
      - name: Verificar professortocat
        id: check_professortocat
        uses: skills/action-keyphrase-checker@v1
        with:
          text: ${{ github.event.comment.body }}
          keyphrase: "professortocat"
          case-sensitive: false
          minimum-occurrences: 1
      - name: Verificar URL do GitHub App
        id: check_alert
        uses: skills/action-keyphrase-checker@v1
        with:
          text: ${{ github.event.comment.body }}
          keyphrase: "https://github.com/apps"
          case-sensitive: false
          minimum-occurrences: 1

  find_exercise:
    name: Encontrar issue do exercício
    uses: dev-pods/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.1.1

  check_step_work:
    name: Verificar trabalho da etapa
    runs-on: ubuntu-latest
    needs: [check_keywords, find_exercise]
    env:
      ISSUE_REPOSITORY: ${{ github.repository }}
      ISSUE_NUMBER: ${{ needs.find_exercise.outputs.issue-number }}

    steps:
      - name: Fazer checkout
        uses: actions/checkout@v4

      - name: Obter templates de resposta
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.7.0

      # INÍCIO: Verificação prática

      - name: Verificar se a URL do GitHub App é válida
        id: check-app-url
        continue-on-error: true
        run: |
          # Obter a URL do GitHub App do corpo do comentário
          url_regex="https://github.com/apps/[^[:space:]]*"
          app_url=$(echo $ISSUE_COMMENT_BODY | grep -oP "$url_regex" | head -n 1)

          # Testar a URL e obter o conteúdo
          echo "Verificando se o GitHub App existe em: $app_url"
          resp_code=$(curl -s -o /dev/null -w "%{http_code}" $app_url)
          echo "Código de resposta: $resp_code"

          # Se a URL do GitHub App não for válida, não foi criada. Comentar na issue e sair
          if [ "$resp_code" -eq 200 ]; then
            echo "GitHub App confirmado existente"
          else
            echo "GitHub App não disponível. Código de resposta: $resp_code"
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_COMMENT_BODY: ${{ github.event.comment.body }}

      # FIM: Verificação prática

      - name: Criar comentário - resultados da etapa
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: exercise-toolkit/markdown-templates/step-feedback/step-results-table.md
          vars: |
            step_number: 3
            results_table:
              - description: "URL do GitHub App é válida"
                passed: ${{ steps.check-app-url.outcome == 'success' }}

      - name: Falhar job se nem todas as verificações passaram
        if: contains(steps.*.outcome, 'failure')
        run: exit 1

  post_next_step_content:
    name: Publicar conteúdo do próximo passo
    needs: [find_exercise, check_step_work]
    runs-on: ubuntu-latest
    env:
      ISSUE_REPOSITORY: ${{ github.repository }}
      ISSUE_NUMBER: ${{ needs.find_exercise.outputs.issue-number }}

    steps:
      - name: Fazer checkout
        uses: actions/checkout@v4

      - name: Obter templates de resposta
        uses: actions/checkout@v4
        with:
          repository: dev-pods/exercise-toolkit
          path: exercise-toolkit
          ref: v0.1.1

      - name: Criar comentário - etapa finalizada
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: exercise-toolkit/markdown-templates/step-feedback/step-finished-prepare-next-step.md
          vars: |
            next_step_number: 4

      - name: Criar comentário - adicionar conteúdo da etapa
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: ${{ env.STEP_4_FILE }}
          vars: |
            login: ${{ github.actor }}

      - name: Criar comentário - acompanhando progresso
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: exercise-toolkit/markdown-templates/step-feedback/watching-for-progress.md

      - name: Desabilitar workflow atual e habilitar o próximo
        run: |
          gh workflow disable "${{github.workflow}}"
          gh workflow enable "Step 4"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
